### ISSUE TITLE
Parallelise the network orbit correction

### ISSUE THREAD

**Issue by basaks** [GeoscienceAustralia/PyRate#75] opened 2016-05-13 00:06 UTC
Implement mpi and multiprocessing for network orbital correction to improve efficiency for large interferogram networks and low `orbfitlksx` and `orbfitlksy` values

**Comment by basaks** [comment] 2017-03-06 23:07
Log info of multilooked interferrogram total memory requirement.
Test and fall back to `independent method` when memory requirement not satisfied.

**Comment by basaks** [comment] 2017-04-21 01:57
Orbital fit method 1(independent method) is now mpi parallel.
Orbital fit method 2 (network method) is not parallel and way forward is captured in  #147.

@mcgarth to decide future development.

**Comment by mcgarth** [comment] 2017-05-22 08:04
MPI/parallel network orb method to be implemented if testing reveals a bottleneck

**Comment by mcgarth** [comment] 2021-04-29 23:06
Closing, the issue is too old and need is not high priority

**Closed by mcgarth** 2021-04-29 23:06 UTC
Labels: enhancement
