### ISSUE TITLE
Feedback from peer review

### ISSUE THREAD

**Issue by mcgarth** [GeoscienceAustralia/PyRate#179] opened 2018-11-05 01:01 UTC
PyRate was submitted to the [IEEE Remote Sensing Code Library](http://rscl-grss.org/about.php) for inclusion. Acceptance is dependent on independent peer review.

Two reviews were received, with both identifying issues with the low pass filter implemented in ```aps.py```:

**Review 1**

*I would like to report to you the review status of the submission entitled PyRate. According to the code description in the website provided by the author, the pyrate program has three command line options corresponding to different parts of the PyRate workflow:*
*1.    prepifg*
*2.    linrate*
*3.    postprocess*
*So far the first part, prepifg, can be executed normally. However, the second part, linrate, runs into error and stops. The shown error message is “ValueError : No points given”. As such, the third part cannot be continued.*

*As to the cause of the error, since the code depends on numerous libraries, it remains to figure out if the problem is with potential mismatch among installed libraries, or with the code itself. We tend to think mismatch is the issue, yet it needs to be proved.*

**Review 2**

*I took two weeks (off and on) to install the software. I finally got it to install without errors. I ran the code using two options: the test case using the pyrate_gamma.conf, and a second case using my unwrapped interferograms. Both cases had identical behavior. They ran through the prepifg stage successfully, then failed during linrate at the "applying spatial low pass filter" stage. The error appears to occur in aps.py in the interpolate_nans_2d function with the error "ValueError: No points given". If you want the full Traceback, I can provide that information*

**Comment by brenmous** [comment] 2019-07-05 03:26
This appears to have been caused by changes in version 2.x of networkx which breaks the minimum spanning tree functionality of PyRate. This was causing linrate to output an array of nans as a product of the minimum spanning tree, hence the 'No points given' error.  This was also causing several tests to fail (see [this Travis build output](https://travis-ci.org/GeoscienceAustralia/PyRate/jobs/301813105)) .

This is fixed by pinning pin networkx to a working version. Will close this issue once these changes have been merged into a new master release.

In future we'll make changes to accomodate networkx 2.x.

**Closed** 2019-07-10 05:06 UTC
Labels: bug

**Comment by brenmous** [comment] 2019-07-10 05:07
solved by #184 

Issue was that networkx now delivers edges() etc. as their own dynamic View class as opposed to lists. There was a guard checking if mst.edges was a list before iterating over them. Modifying this guard to check if the mst edges are an EdgeView fixes the issues. Info [here](https://networkx.github.io/documentation/stable/release/migration_guide_from_1.x_to_2.0.html).
Q: why does this guard not raise an exception instead of returning an empty (or nan/False filled) array?
